# Generated by Django 5.0.6 on 2024-05-15 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(max_length=500)),
                ('center', models.CharField(max_length=500)),
                ('date', models.DateTimeField(auto_now=True)),
                ('subject', models.TextField()),
                ('description', models.TextField()),
                ('oncall', models.BooleanField(default=False)),
            ],
        ),
    ]
